package Enums;

public enum ApplicationStatusEnum {
    PENDING,
    UNDER_REVIEW,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CONDUCTED,
    OFFER_EXTENDED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    HIRED,
    NOT_SELECTED,
    WITHDRAWN
}
